import Link from "next/link";
import { ArrowLeft, ExternalLink, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { demoDeclarations } from "@/lib/demo-data";
import { money } from "@/lib/utils";

export default async function DeclarationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const declaration = demoDeclarations.find((item) => item.id === id) ?? demoDeclarations[0];
  return <div className="mx-auto max-w-5xl"><Button asChild variant="ghost" className="mb-4 -ml-3"><Link href="/declaraciones"><ArrowLeft className="size-4" />Volver a declaraciones</Link></Button><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><h1 className="text-2xl font-bold tracking-[-0.02em]">Declaración de {declaration.period}</h1><Badge className="bg-success/10 text-success">Procesada</Badge></div><p className="mt-2 text-sm text-muted">Operación {declaration.operationNumber}</p></div><Button variant="secondary"><ExternalLink className="size-4" />Ver documento original</Button></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><section className="panel p-5"><h2 className="font-semibold">Información general</h2><dl className="mt-5 grid gap-x-8 gap-y-5 sm:grid-cols-2">{[["Tipo",declaration.declarationType],["Periodo",declaration.period],["Fecha de presentación",declaration.filingDate],["Número de operación",declaration.operationNumber]].map(([term,value])=><div key={term}><dt className="text-sm text-muted">{term}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl><div className="mt-6 border-t border-border pt-5"><h2 className="font-semibold">Importes encontrados</h2><dl className="mt-4 divide-y divide-border">{[["ISR",declaration.isr],["IVA",declaration.iva],["Total pagado",declaration.totalPaid]].map(([term,value])=><div key={String(term)} className="flex justify-between py-3"><dt className="text-muted">{term}</dt><dd className="tabular font-semibold">{typeof value === "number" ? money.format(value) : "No identificado"}</dd></div>)}</dl></div></section><aside className="panel p-5"><span className="grid size-11 place-items-center rounded-[10px] bg-primary/10 text-primary"><FileText className="size-5" /></span><h2 className="mt-4 font-semibold">Archivo original</h2><p className="mt-1 break-all text-sm text-muted">{declaration.filename}</p><p className="mt-4 text-xs leading-5 text-muted">El documento permanece privado. El acceso requiere una sesión válida o un enlace firmado temporal.</p></aside></div></div>;
}
